### ISSUE TITLE
Peer-to-Peer code review Stand-Up meeting

### ISSUE THREAD

**Issue by srueda27** [Meltrust/forms-project#7]

**Comment by srueda27** [comment]
Excellent work, Congratulations!

**Comment by EdCrux** [comment]
You apply Flexbox properties very well!

**Comment by dxania** [comment]
Great work.
Awesome Readme.md
You can increase the space between the 3 logo's
Nice commit messages

**Comment by simondebbarma** [comment]
# 👌👌👌 Excellent 🙌🏼🙌🏼🙌🏼
---
### 👍🏼 Pros
- It's responsive
- Everything looks well done
- The cream of the crop.

**🍪 Extra Cookies for nifty JS code usage**

---
<img src="https://media.giphy.com/media/3o752lVfb8bwSchZcI/giphy.gif" width="100%" >

**Comment by codecell** [comment]
Nice job from you and your teammate,
but I observed the following 
- the production version and the development version are not the same; the one you have in life demo has the labels centre-aligned why your local demo has the labels left-aligned.
- the file structure can also be more cleaned up, you have images in icons and images folder

**Comment by Meltrust** [comment]
### Codecell:

> 
> 
> Nice job from you and your teammate,
> but I observed the following
> 
>     * the production version and the development version are not the same; the one you have in life demo has the labels centre-aligned why your local demo has the labels left-aligned.
> 
>     * the file structure can also be more cleaned up, you have images in icons and images folder


**Corrected both things Codecell.** I just can't describe how grateful I am by your input because the first issue I wouldn't have noticed if you hadn't told me about it.  We noticed that this issue was presenting itself in Chrome, but not in Firefox (I use Firefox).  So we made the corresponding changes but forgot to commit them to the master branch.  Now it's done thanks again.




### To all of you:

As a person just starting out in the coding world your compliments for my second project (as a group) were so flattering that I almost shed a tear (the Gordon Ramsay's meme was special for me because I have a passion for cooking too).

_Marian If you are reading this, good job partner!!._

Thanks guys!! : ..)

**Comment by simondebbarma** [comment]
# You're Welcome
---

<img src="https://media.giphy.com/media/WAfGpVI1pI3e/giphy.gif" width="100%">
